url: https://pubinv.github.io/actnetopt
repourl: https://github.com/PubInv/actnetopt
projecttitle: "Actuator Net Optimization"
featuretitle: "Actuator Net Optimization"
featurelink: https://pubinv.github.io/actnetpot